name: BLACKSTONE_9
title: BLACKSTONE_9
domain: maulbeetle.github.io
url: maulbeetle.github.io
#url: www.blackstone9.net
baseurl: /maulbeetle.github.io/blackstone_9/
description: Something is stirring in the warp...
header_ascii: |
  ██████╗ ██╗      █████╗  ██████╗██╗  ██╗███████╗████████╗ ██████╗ ███╗   ██╗███████╗        █████╗ 
  ██╔══██╗██║     ██╔══██╗██╔════╝██║ ██╔╝██╔════╝╚══██╔══╝██╔═══██╗████╗  ██║██╔════╝       ██╔══██╗
  ██████╔╝██║     ███████║██║     █████╔╝ ███████╗   ██║   ██║   ██║██╔██╗ ██║█████╗         ╚██████║
  ██╔══██╗██║     ██╔══██║██║     ██╔═██╗ ╚════██║   ██║   ██║   ██║██║╚██╗██║██╔══╝          ╚═══██║
  ██████╔╝███████╗██║  ██║╚██████╗██║  ██╗███████║   ██║   ╚██████╔╝██║ ╚████║███████╗███████╗█████╔╝
  ╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝   ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚══════╝╚════╝ 
                                                                                             




                                                                                                              
                                                                                                              
                                                                                                              

